### PR TITLE
Fix bug in constructor and refactor validation logic

### PR DESCRIPTION
**Pull request by gwmccull**
Fixed a bug in the constructor of the InputComponent.
```this.valid = props.validationFunction(value, this);```
was returning an error of `value is undefined`

In the process, I combined the two blocks of validation code since they were nearly the same.

### CODE REVIEW

**Comment by MichaelCereda** [comment]
Hi, thanks for your PR. 
I'm going to check it and merge late tonight.

**Comment by gwmccull** [comment]
Thanks for having a look at my PRs.  I'm trying to use this library for a work project so I have a little time to fix things and push the changes back to you but not a lot as I have a deadline to get this form out the door :-)

**Comment by MichaelCereda** [comment]
Yes.. Of course, I'll try to be as fast as possible.
Thanks for your time... It's nice to have some help sometimes :)
Did you have some  problems with the library?
Any ideas /enhancement?
I'm using it on production too so as far I can tell it's very stable.
I'm going to release a big update soon (I think next week).
I'll also merge your PRs tomorrow... Sorry I'm traveling right now.
Have a nice day ;)

On Fri, Jun 24, 2016, 3:39 AM Garrett McCullough <notifications@github.com>
wrote:

> Thanks for having a look at my PRs. I'm trying to use this library for a
> work project so I have a little time to fix things and push the changes
> back to you but not a lot as I have a deadline to get this form out the
> door :-)
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/MichaelCereda/react-native-form-generator/pull/14#issuecomment-228234698>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAGjfqq4gDOWMGhKliAi--Pl3PMHgcgzks5qOzVQgaJpZM4I9M7D>
> .
>
-- 
Michael Cereda
http://michaelcereda.com

**Comment by gwmccull** [comment]
Hey, thanks for getting the project off to a great start.

I found one small bug (which is in this PR) and I had a few ideas for enhancements (which are in the other PR).

I had actually started working on a very similar project this week.  I'd gotten as far as the input and half-way through a form component before I found your project.  Since yours was further along and had other widgets, I decided to recreate my work using your library.  It went pretty smoothly.

You'll see the enhancements that I needed for my use case in the other PR.

Basically, I thought it made sense for each component to know if it's in a valid state or not, based either on it's value or the value[s] of its child[ren].  If you take this concept all the way up to the form level, then blocking/allowing a submit action becomes pretty easy.

Besides the work in the two PRs, I also built a custom component that wraps an input component and an error message, so that if the field is blank/invalid, the error appears above the text box and a red border is added to the text box.

If you're looking for more help, let me know.  I might be able to spare some time.

**Pull request merged**
